[package]
name = "rust_dbg"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8"
regex = "1.11"

debruijn = { git = "https://github.com/flopau76/rust-debruijn.git", branch = "master" }

# command line interface
clap = { version = "4.5", features = ["derive"] }

# serialisation
serde = "^1"
bincode = { version = "^2", features = ["serde"] }

# parallelisation
rayon = "1.10"
chrono = "0.4.41"
