[package]
name = "rust_dbg"
version = "0.1.0"
edition = "2021"

[dependencies]
packed-seq = "3"
boomphf = { version = "0.6", features = ["serde"] }
serde = "1"
bincode = "1.3"

needletail = "0.6"
clap = { version = "4.5", features = ["derive"] }
chrono = "0.4"

[dev-dependencies]
rand = "0.9"