[package]
name = "rust_dbg"
version = "0.1.0"
edition = "2021"

[dependencies]
debruijn = { git = "https://github.com/flopau76/rust-debruijn.git", branch = "master" }

# command line interface
clap = { version = "4.5", features = ["derive"] }

# serialisation
serde = "1"
bincode = "1.3"

# plots
plotters = "0.3"

# misc: display date/time
chrono = "0.4"