[package]
name = "rust_dbg"
version = "0.1.0"
edition = "2021"

[dependencies]
needletail = "0.6"
packed-seq = "3"
boomphf = { version = "0.6", features = ["serde"] }
smallvec = "1"
clap = { version = "4.5", features = ["derive"] }

[dev-dependencies]
rand = "0.9"