[package]
name = "rust_dbg"
version = "0.1.0"
edition = "2024"

[dependencies]
rustc-hash = "2.1.1"
ahash = "0.8.11"

debruijn = { git = "https://github.com/flopau76/rust-debruijn.git", branch = "patch-1" }

serde = "^1"
bincode = { version = "^2", features = ["serde"] }
rayon = "1.10.0"