[package]
name = "rust_dbg"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.11"
regex = "1.11.1"

debruijn = { git = "https://github.com/flopau76/rust-debruijn.git", branch = "patch-flo" }

# for parallelisation
serde = "^1"
bincode = { version = "^2", features = ["serde"] }
rayon = "1.10.0"

rand = "0.9.1"